local actor = db.actor
local ini = system_ini()
function use(obj)
	local obj_sect = obj:section()
	if obj_sect == "pda_stalk_leader" then
		--pda_ui.on_use(obj)
		local sss = se_respawn.parse_names(ini:r_string(obj_sect, "infop_on_use"))
		for _,v in pairs(sss) do
			actor:give_info_portion(v)
		end
		news_manager.send_tip(actor, "saved_data", nil, "stalker", nil, 4000)
		alife():create(obj_sect, db.actor:position(), 1, db.actor:game_vertex_id(), db.actor:id())
	end
end
